### ISSUE TITLE
Cannot set suppress_export

### ISSUE THREAD

**Issue by pifuchs** [infopark/reactor#14]
Is it possible that setting "suppress_export" is not supported?

I can read the value just fine: 
<pre>[5] pry(main)> o.suppress_export
=> 0</pre>

But when I set it to "1" and "save!" the object I get an error message:
<pre>Reactor::Cm::XmlRequestError: <phrase>[030012] 'suppress_export' kann nicht gesetzt werden, falscher Bezeichner.</phrase></pre>

**Comment by tomaszp-infopark** [comment]
I've just released `1.12.0.beta1` which contains this feature. Would you mind taking a look?
