### ISSUE TITLE
Define equal values for different languages

### ISSUE THREAD

**Issue by heikobornholdt** [infopark/reactor#16]
With the Tcl API I can create a new attribute an specify, for example that `title.de` and `title.en` have the equal value `Foo`.
How can I do this with a reactor migration?

**Comment by tomaszp-infopark** [comment]
It is sadly a known issue, which would be extremely hard to resolve and even harder to create a backwards-compatible solution for.

In this case I would recommend the following:

```ruby
create_attribute :name => 'example', :type => 'string' do
  set :title, {"Kindergarten"=>{:lang=>:en}, "École Maternelle"=>{:lang=>:fr}}
end
update_attribute :name => 'example' do
  set :title, {"Kindergarten"=>{:lang=>:de}}
end
```

which will result in:

```
root@localhost:5782 test(CM)> attribute withName example description
{
    "title.de" = Kindergarten;
    "title.en" = Kindergarten;
    "title.fr" = "École Maternelle";
    editField = {
        length = 65;
        type = textfield;
    };
    isSearchableInCM = 0;
    isSearchableInTE = 0;
    name = example3;
    title = Kindergarten;
    type = string;
}
```

**Comment by heikobornholdt** [comment]
Thanks! That workaround will help us.

I would suggest the following syntax to fix the problem. In my mind, that should make the backwards-compatibility possible.

    create_attribute :name => 'example', :type => 'string' do
      set :title, {"Kindergarten"=>{:lang=>[:de, :en]}, "École Maternelle"=>  {:lang=>:fr}}
    end

**Comment by tomaszp-infopark** [comment]
Thanks for your suggestion, I will look into it!
