### ISSUE TITLE
Create, update, delete attribute groups?

### ISSUE THREAD

**Issue by heikobornholdt** [infopark/reactor#19]
Is it possible to create, update, delete attribute groups with reactor?

**Comment by tomaszp-infopark** [comment]
Attribute groups are unsupported at the moment.

It would be very helpful if you could provide your use cases for the attribute groups.

**Comment by heikobornholdt** [comment]
We need this feature for cm migrations. Classes and attributes can be handled with migrations, but attribute groups are missing atm.

**Comment by tomaszp-infopark** [comment]
I've just released `1.12.0.beta1` which contains this feature. Would you mind taking a look?

**Comment by heikobornholdt** [comment]
Migrating attribute groups also work well. Thank you.
