### ISSUE TITLE
remove warnings for Ruby 2.4

### ISSUE THREAD

**Issue by sprestel** [infopark/reactor#24]
`infopark_reactor-1.26.0/lib/reactor/legacy.rb:49: warning: constant ::Fixnum is deprecated`

**Comment by tprzedmojski** [comment]
Wahrscheinlich würde es helfen `Fixnum` gegen `Integer` zu tauschen.

**Comment by ronaldmueller** [comment]
@antonmezin jetzt auch der Uni HH (Herrn Mundry) beim Test des infopark_reactor-1.27.0.rc1 aufgefallen.

siehe auch
https://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html
https://www.ruby-lang.org/de/news/2016/12/25/ruby-2-4-0-released/
